In [12]:
#from urllib.parse import urlencode
#from pandas_datareader import data

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

from datetime import date
from datetime import datetime
from datetime import timedelta

from tsfresh import extract_features
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

from tsfresh.transformers import RelevantFeatureAugmenter

In [28]:
from pandas_datareader import data

In [29]:
#! pip install git+https://github.com/pydata/pandas-datareader.git

In [13]:
try:
    from urllib import urlencode
except ImportError:
    from urllib.parse import urlencode

In [158]:
def load_data(tickers, start_date, end_date):
      """
      INPUT:
      tickers : list containing the tickers of the stocks whose prices will be predicted
      start_date : initial date to gather data
      end_data : final date to gather data
      OUTPUT:
      prices_base : dataframe containing the adjusted closing price for the stocks
                    on the desired time frame
      """
      df = data.DataReader(
          tickers,
          'yahoo',
          start_date,
          end_date)

      df = pd.DataFrame(panel_data)
      df = panel_data['Adj Close']

      df_prices = df.stack()
      df_prices = pd.DataFrame(df_prices)
      df_prices.columns = ['Prices']

      df_prices.reset_index(inplace=True)
      df_prices = df_prices.sort_values(by = ['Symbols','Date'])
      
      

      return df_prices

In [159]:
df =download_prices(['TSLA','AAPL'], 
                      '2019-01-01', 
                      '2019-12-31')

In [160]:
df.head()

        Date Symbols     Prices
1 2019-01-02    AAPL  38.277531
3 2019-01-03    AAPL  34.464802
5 2019-01-04    AAPL  35.936081
7 2019-01-07    AAPL  35.856091
9 2019-01-08    AAPL  36.539619

In [161]:
def create_time_features(df):
    df.rename(columns={'Date':'ds'},inplace = True )
    df['dayofweek'] = df['ds'].dt.dayofweek
    df['quarter'] = df['ds'].dt.quarter
    df['month'] = df['ds'].dt.month
    df['year'] = df['ds'].dt.year
    df['dayofyear'] = df['ds'].dt.dayofyear
    df['sin_day'] = np.sin(df['dayofyear'])
    df['cos_day'] = np.cos(df['dayofyear'])
    df['dayofmonth'] = df['ds'].dt.day
    df['weekofyear'] = df['ds'].dt.weekofyear
    df=df.sort_values('ds')
    return df

In [162]:
df = create_time_features(df)

/Users/dgitahi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: FutureWarning:

Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

In [164]:
df.head()

,ds,Symbols,Prices,dayofweek,quarter,month,year,dayofyear,sin_day,cos_day,dayofmonth,weekofyear
1,2019-01-02,AAPL,38.277531,2,1,1,2019,2,0.909297,-0.416147,2,1
0,2019-01-02,TSLA,62.023998,2,1,1,2019,2,0.909297,-0.416147,2,1
3,2019-01-03,AAPL,34.464802,3,1,1,2019,3,0.141120,-0.989992,3,1
2,2019-01-03,TSLA,60.071999,3,1,1,2019,3,0.141120,-0.989992,3,1
5,2019-01-04,AAPL,35.936081,4,1,1,2019,4,-0.756802,-0.653644,4,1

#### EDA

In [ ]:
for ticker in  


fig = go.Figure(layout={'width' :1000,'height':500})

fig.add_trace(go.Scatter(x=df.ds,y=df.yhat,
                    mode='lines+markers',
                    name='FORECAST'))

#     fig.add_trace(go.Scatter(x=df.ds,y=df.yhat_lower,
#                         mode='lines+markers',
#                         name='lower_boundary'))

#     fig.add_trace(go.Scatter(x=df.ds,y=df.yhat_upper,
#                         mode='lines+markers',
#                         name='upper_boundary'))



fig.add_trace(go.Scatter(x=df.ds ,y=df.actual,
                    mode='lines+markers',
                    name='ACTUAL'))
fig.update_layout(title = 'Bungoma',
                 yaxis_title = "Number of Customers")

#fig.update_yaxes(range=[10000, 800000])